### ISSUE TITLE
BetterTTV Emotes

### ISSUE THREAD

**Issue by arnoudbevers** [Simego/TwitchEmotes4WhatsApp#1]
Is it possible to support BetterTTV Emotes?

**Comment by Simego** [comment]
The BetterTTV have a subscription on their website, like FrankerfaceZ has

**Comment by arnoudbevers** [comment]
I know, but is it possible to have them replaced in WebWhatsapp also?

**Comment by Simego** [comment]
it is, just have to check for the bttv emotes list like i do with normal twitch emotes list, as you can also do with sub emotes but since it's a huge list, most ppl don't do it (even BTTV that's why you can only use emotes from your channel only in your channel)
